language: java
jdk:
  - oraclejdk9

sudo: false
dist: trusty
addons:
  apt:
    packages:
      - oracle-java9-installer

cache:
  directories:
  - $HOME/.m2
  
install: true

script: "mvn clean install"

before_deploy:
  - export RELEASE_FILE=$(ls Dist/target/cognizant-intelligent-test-scripter-*.zip)
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:  $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
